/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	MutationFunction,
	QueryFunction,
	QueryKey,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type {
	OpenaiControllerChat201,
	OpenaiControllerCreate200Item,
	OpenaiControllerCreateGraph200Item,
	OpenaiControllerDashboardDataGet200,
	RequestBodyOpenaiDto,
} from "./models";
import { authInstance } from "../../instances/authInstance";
import type { ErrorType } from "../../instances/authInstance";

export const openaiControllerCreate = (requestBodyOpenaiDto: RequestBodyOpenaiDto) => {
	return authInstance<OpenaiControllerCreate200Item[] | void>({
		url: `/api/openai`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: requestBodyOpenaiDto,
	});
};

export const getOpenaiControllerCreateMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof openaiControllerCreate>>,
		TError,
		{ data: RequestBodyOpenaiDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof openaiControllerCreate>>,
	TError,
	{ data: RequestBodyOpenaiDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof openaiControllerCreate>>,
		{ data: RequestBodyOpenaiDto }
	> = (props) => {
		const { data } = props ?? {};

		return openaiControllerCreate(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type OpenaiControllerCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof openaiControllerCreate>>
>;
export type OpenaiControllerCreateMutationBody = RequestBodyOpenaiDto;
export type OpenaiControllerCreateMutationError = ErrorType<unknown>;

export const useOpenaiControllerCreate = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof openaiControllerCreate>>,
		TError,
		{ data: RequestBodyOpenaiDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof openaiControllerCreate>>,
	TError,
	{ data: RequestBodyOpenaiDto },
	TContext
> => {
	const mutationOptions = getOpenaiControllerCreateMutationOptions(options);

	return useMutation(mutationOptions);
};
export const openaiControllerCreateGraph = (requestBodyOpenaiDto: RequestBodyOpenaiDto) => {
	return authInstance<OpenaiControllerCreateGraph200Item[] | void>({
		url: `/api/openai/graph`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: requestBodyOpenaiDto,
	});
};

export const getOpenaiControllerCreateGraphMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof openaiControllerCreateGraph>>,
		TError,
		{ data: RequestBodyOpenaiDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof openaiControllerCreateGraph>>,
	TError,
	{ data: RequestBodyOpenaiDto },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof openaiControllerCreateGraph>>,
		{ data: RequestBodyOpenaiDto }
	> = (props) => {
		const { data } = props ?? {};

		return openaiControllerCreateGraph(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type OpenaiControllerCreateGraphMutationResult = NonNullable<
	Awaited<ReturnType<typeof openaiControllerCreateGraph>>
>;
export type OpenaiControllerCreateGraphMutationBody = RequestBodyOpenaiDto;
export type OpenaiControllerCreateGraphMutationError = ErrorType<unknown>;

export const useOpenaiControllerCreateGraph = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof openaiControllerCreateGraph>>,
		TError,
		{ data: RequestBodyOpenaiDto },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof openaiControllerCreateGraph>>,
	TError,
	{ data: RequestBodyOpenaiDto },
	TContext
> => {
	const mutationOptions = getOpenaiControllerCreateGraphMutationOptions(options);

	return useMutation(mutationOptions);
};
export const openaiControllerChat = (openaiControllerChatBody: string[]) => {
	return authInstance<OpenaiControllerChat201>({
		url: `/api/openai/chat`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: openaiControllerChatBody,
	});
};

export const getOpenaiControllerChatMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof openaiControllerChat>>,
		TError,
		{ data: string[] },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof openaiControllerChat>>,
	TError,
	{ data: string[] },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof openaiControllerChat>>,
		{ data: string[] }
	> = (props) => {
		const { data } = props ?? {};

		return openaiControllerChat(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type OpenaiControllerChatMutationResult = NonNullable<
	Awaited<ReturnType<typeof openaiControllerChat>>
>;
export type OpenaiControllerChatMutationBody = string[];
export type OpenaiControllerChatMutationError = ErrorType<unknown>;

export const useOpenaiControllerChat = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof openaiControllerChat>>,
		TError,
		{ data: string[] },
		TContext
	>;
}): UseMutationResult<
	Awaited<ReturnType<typeof openaiControllerChat>>,
	TError,
	{ data: string[] },
	TContext
> => {
	const mutationOptions = getOpenaiControllerChatMutationOptions(options);

	return useMutation(mutationOptions);
};
export const openaiControllerDashboardDataGet = (id: string, signal?: AbortSignal) => {
	return authInstance<OpenaiControllerDashboardDataGet200>({
		url: `/api/openai/dashboardDataGet/${id}`,
		method: "GET",
		signal,
	});
};

export const getOpenaiControllerDashboardDataGetQueryKey = (id: string) => {
	return [`/api/openai/dashboardDataGet/${id}`] as const;
};

export const getOpenaiControllerDashboardDataGetQueryOptions = <
	TData = Awaited<ReturnType<typeof openaiControllerDashboardDataGet>>,
	TError = ErrorType<unknown>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof openaiControllerDashboardDataGet>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getOpenaiControllerDashboardDataGetQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof openaiControllerDashboardDataGet>>> = ({
		signal,
	}) => openaiControllerDashboardDataGet(id, signal);

	return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof openaiControllerDashboardDataGet>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type OpenaiControllerDashboardDataGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof openaiControllerDashboardDataGet>>
>;
export type OpenaiControllerDashboardDataGetQueryError = ErrorType<unknown>;

export const useOpenaiControllerDashboardDataGet = <
	TData = Awaited<ReturnType<typeof openaiControllerDashboardDataGet>>,
	TError = ErrorType<unknown>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof openaiControllerDashboardDataGet>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const queryOptions = getOpenaiControllerDashboardDataGetQueryOptions(id, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
};
