/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { AIDashboardDtoType } from "./aIDashboardDtoType";

export interface AIDashboardDto {
	createdAt: string;
	id: string;
	isExist: boolean;
	prompt: string;
	query: string;
	title: string;
	type: AIDashboardDtoType;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
}
