/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type AIDashboardDtoType = (typeof AIDashboardDtoType)[keyof typeof AIDashboardDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AIDashboardDtoType = {
	Table: "Table",
	Chart: "Chart",
} as const;
