/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Agridulture API
 * Enhance your business with Agriculture API
 * OpenAPI spec version: 1.0
 */

export interface BlackSoilDto {
	address: string;
	cotton: number;
	createdAt: string;
	id: string;
	isExist: boolean;
	latitude: number;
	longitude: number;
	maize: number;
	rice: number;
	sugarcane: number;
	sunflower: number;
	/** @nullable */
	updatedAt: string | null;
	wheat: number;
}
