/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CompanyDto } from "./companyDto";

export type CompanyControllerUpdate201AllOf = {
	result?: CompanyDto;
};
