/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreatePaymentsDtoPaymentType } from "./createPaymentsDtoPaymentType";

export interface CreatePaymentsDto {
	amount: number;
	invoice_id: string;
	/** @nullable */
	notes?: string | null;
	payment_type?: CreatePaymentsDtoPaymentType;
	paymentDate?: string;
	paymentDetails_id: string;
	/** @nullable */
	private_notes?: string | null;
	/** @nullable */
	reference_number?: string | null;
	user_id: string;
}
