/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { OmitCreatePlanFeatureDto } from "./omitCreatePlanFeatureDto";

export interface CreatePlanWithFeaturesDto {
	days: number;
	description: string;
	features: OmitCreatePlanFeatureDto[];
	is_active: boolean;
	name: string;
	price: number;
}
