/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Agridulture API
 * Enhance your business with Agriculture API
 * OpenAPI spec version: 1.0
 */

export interface CreateBlackSoilDto {
	address: string;
	cotton: number;
	latitude: number;
	longitude: number;
	maize: number;
	rice: number;
	sugarcane: number;
	sunflower: number;
	wheat: number;
}
