/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateGateWayDetailsDtoType } from "./createGateWayDetailsDtoType";

export interface CreateGateWayDetailsDto {
	enabled?: boolean;
	/** @nullable */
	key?: string | null;
	/** @nullable */
	secret?: string | null;
	type: CreateGateWayDetailsDtoType;
	user_id: string;
}
