/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type CreateProductDtoType = (typeof CreateProductDtoType)[keyof typeof CreateProductDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProductDtoType = {
	Service: "Service",
	Good: "Good",
} as const;
