/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface CreateUserCompany {
	companyName: string;
	/** @nullable */
	currency_id?: string | null;
	email: string;
	/** @nullable */
	name?: string | null;
	password: string;
	/** @nullable */
	phone?: string | null;
}
