/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Agridulture API
 * Enhance your business with Agriculture API
 * OpenAPI spec version: 1.0
 */

export interface CreateRedSoilDto {
	address: string;
	cereal: number;
	groundnut: number;
	kagi: number;
	latitude: number;
	longitude: number;
	pulse: number;
	vegetable: number;
}
