/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type CreateInvoiceWithProductsRecurring =
	| (typeof CreateInvoiceWithProductsRecurring)[keyof typeof CreateInvoiceWithProductsRecurring]
	| null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateInvoiceWithProductsRecurring = {
	Daily: "Daily",
	Weekly: "Weekly",
	Monthly: "Monthly",
	Quarterly: "Quarterly",
	HalfYearly: "HalfYearly",
	Yearly: "Yearly",
} as const;
