/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateProductDtoType } from "./createProductDtoType";

export interface CreateProductDto {
	currency_id: string;
	/** @nullable */
	description?: string | null;
	/** @nullable */
	hsnCode_id?: string | null;
	name: string;
	price: number;
	/** @nullable */
	tax_id?: string | null;
	type: CreateProductDtoType;
	unit_id: string;
	user_id: string;
}
