/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface CreateBillingAddressDto {
	address: string;
	city: string;
	country_id: string;
	state_id: string;
	zip: string;
}
