/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateBillingAddressDto } from "./createBillingAddressDto";
import type { CreateCustomerWithAddressDtoOption } from "./createCustomerWithAddressDtoOption";
import type { CreateShippingAddressDto } from "./createShippingAddressDto";

export interface CreateCustomerWithAddressDto {
	billingDetails?: CreateBillingAddressDto;
	currencies_id: string;
	display_name: string;
	email: string;
	name: string;
	option: CreateCustomerWithAddressDtoOption;
	/** @nullable */
	phone?: string | null;
	shippingDetails?: CreateShippingAddressDto;
	user_id: string;
	/** @nullable */
	website?: string | null;
}
