/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface CreateUserPlansDto {
	end_date: string;
	plan_id: string;
	session_id?: string;
	start_date: string;
	status?: boolean;
	user_id: string;
}
