/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface CurrenciesDto {
	code: string;
	createdAt: string;
	id: string;
	isExist: boolean;
	name: string;
	short_code: string;
	symbol: string;
	/** @nullable */
	updatedAt: string | null;
}
