/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { BillingAddress } from "./billingAddress";
import type { Currencies } from "./currencies";
import type { CustomerOption } from "./customerOption";
import type { ShippingAddress } from "./shippingAddress";
import type { User } from "./user";

export interface Customer {
	billingAddress?: BillingAddress;
	billingAddress_id: string;
	createdAt: string;
	currencies?: Currencies;
	currencies_id: string;
	display_name: string;
	email: string;
	id: string;
	isExist: boolean;
	name: string;
	option: CustomerOption;
	/** @nullable */
	phone: string | null;
	shippingAddress?: ShippingAddress;
	shippingAddress_id: string;
	/** @nullable */
	updatedAt: string | null;
	user?: User;
	user_id: string;
	/** @nullable */
	website: string | null;
}
