/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { AIDashboardDto } from "./aIDashboardDto";

export type DashboardsControllerCreate200AllOf = {
	result?: AIDashboardDto;
};
