/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { ExpensesControllerUpdate200AllOf } from "./expensesControllerUpdate200AllOf";

export type ExpensesControllerUpdate200 = SuccessResponseDto & ExpensesControllerUpdate200AllOf;
