/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type ExpensesDtoCategory = (typeof ExpensesDtoCategory)[keyof typeof ExpensesDtoCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExpensesDtoCategory = {
	Travel: "Travel",
	Food: "Food",
	Office: "Office",
	Rent: "Rent",
	Salary: "Salary",
	Other: "Other",
} as const;
