/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { ExpensesCategory } from "./expensesCategory";
import type { Currencies } from "./currencies";
import type { User } from "./user";
import type { Vendors } from "./vendors";

export interface Expenses {
	amount: number;
	category: ExpensesCategory;
	createdAt: string;
	currency?: Currencies;
	currency_id: string;
	expenseDate: string;
	id: string;
	isExist: boolean;
	/** @nullable */
	notes: string | null;
	/** @nullable */
	receipt_url: string | null;
	/** @nullable */
	updatedAt: string | null;
	user?: User;
	user_id: string;
	vendor?: Vendors;
	vendor_id: string;
}
