/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { GatewaydetailsControllerUpdate200AllOf } from "./gatewaydetailsControllerUpdate200AllOf";

export type GatewaydetailsControllerUpdate200 = SuccessResponseDto &
	GatewaydetailsControllerUpdate200AllOf;
