/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { GateWayDetailsDtoType } from "./gateWayDetailsDtoType";

export interface GateWayDetailsDto {
	createdAt: string;
	enabled: boolean;
	id: string;
	isExist: boolean;
	/** @nullable */
	key: string | null;
	/** @nullable */
	secret: string | null;
	type: GateWayDetailsDtoType;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
}
