/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateVendorsBillingAddressDto } from "./createVendorsBillingAddressDto";

export interface GetVendorsWithAddressDto {
	billingAddress?: CreateVendorsBillingAddressDto;
	billingAddress_id: string;
	createdAt: string;
	display_name: string;
	email: string;
	id: string;
	isExist: boolean;
	name: string;
	/** @nullable */
	phone: string | null;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
	/** @nullable */
	website: string | null;
}
