/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type InvoiceDtoPaidStatus = (typeof InvoiceDtoPaidStatus)[keyof typeof InvoiceDtoPaidStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceDtoPaidStatus = {
	Paid: "Paid",
	Unpaid: "Unpaid",
} as const;
