/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { InvoicesettingsControllerUpdate200AllOf } from "./invoicesettingsControllerUpdate200AllOf";

export type InvoicesettingsControllerUpdate200 = SuccessResponseDto &
	InvoicesettingsControllerUpdate200AllOf;
