/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { InvoiceProductsHsnCode } from "./invoiceProductsHsnCode";
import type { Invoice } from "./invoice";
import type { Product } from "./product";
import type { InvoiceProductsTax } from "./invoiceProductsTax";

export interface InvoiceProducts {
	createdAt: string;
	/** @nullable */
	hsnCode?: InvoiceProductsHsnCode;
	/** @nullable */
	hsnCode_id: string | null;
	id: string;
	invoice?: Invoice;
	invoice_id: string;
	isExist: boolean;
	price: number;
	product?: Product;
	product_id: string;
	quantity: number;
	/** @nullable */
	tax?: InvoiceProductsTax;
	/** @nullable */
	tax_id: string | null;
	total: number;
	/** @nullable */
	updatedAt: string | null;
}
