/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Customer } from "./customer";
import type { InvoiceWithAllDataDtoPaidStatus } from "./invoiceWithAllDataDtoPaidStatus";
import type { InvoiceWithAllDataDtoPayment } from "./invoiceWithAllDataDtoPayment";
import type { InvoiceProducts } from "./invoiceProducts";
import type { InvoiceWithAllDataDtoRecurring } from "./invoiceWithAllDataDtoRecurring";
import type { InvoiceWithAllDataDtoTax } from "./invoiceWithAllDataDtoTax";
import type { InvoiceWithAllDataDtoTemplate } from "./invoiceWithAllDataDtoTemplate";
import type { User } from "./user";

export interface InvoiceWithAllDataDto {
	/** @nullable */
	companyAddress?: string | null;
	createdAt: string;
	customer?: Customer;
	customer_id: string;
	/** @nullable */
	customerBillingAddress?: string | null;
	/** @nullable */
	customerShippingAddress?: string | null;
	date: string;
	/** @nullable */
	discountPercentage: number | null;
	due_amount: number;
	due_date: string;
	id: string;
	invoice_number: string;
	is_recurring: boolean;
	isExist: boolean;
	/** @nullable */
	notes: string | null;
	paid_amount: number;
	paid_status: InvoiceWithAllDataDtoPaidStatus;
	/** @nullable */
	payment?: InvoiceWithAllDataDtoPayment;
	/** @nullable */
	paymentId: string | null;
	product?: InvoiceProducts[];
	/** @nullable */
	recurring: InvoiceWithAllDataDtoRecurring;
	/** @nullable */
	reference_number: string | null;
	/** @nullable */
	status: string | null;
	sub_total: number;
	/** @nullable */
	tax?: InvoiceWithAllDataDtoTax;
	/** @nullable */
	tax_id: string | null;
	/** @nullable */
	template?: InvoiceWithAllDataDtoTemplate;
	/** @nullable */
	template_id: string | null;
	/** @nullable */
	template_url: string | null;
	total: number;
	/** @nullable */
	updatedAt: string | null;
	user?: User;
	user_id: string;
}
