/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { InvoicesettingsControllerCreate201AllOf } from "./invoicesettingsControllerCreate201AllOf";

export type InvoicesettingsControllerCreate201 = SuccessResponseDto &
	InvoicesettingsControllerCreate201AllOf;
