/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { InvoiceDto } from "./invoiceDto";

export type InvoiceControllerCreate201AllOf = {
	result?: InvoiceDto;
};
