/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface NotificationDto {
	body: string;
	createdAt: string;
	id: string;
	isExist: boolean;
	/** @nullable */
	meta: string | null;
	/** @nullable */
	metaType: string | null;
	read: boolean;
	title: string;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
}
