/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface OmitCreateQuotationProductsDto {
	/** @nullable */
	hsnCode_id?: string | null;
	price: number;
	product_id: string;
	quantity: number;
	/** @nullable */
	tax_id?: string | null;
	total: number;
}
