/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Invoice } from "./invoice";
import type { PaymentsPaymentType } from "./paymentsPaymentType";
import type { PaymentDetails } from "./paymentDetails";
import type { User } from "./user";

export interface Payments {
	amount: number;
	createdAt: string;
	id: string;
	invoice?: Invoice;
	invoice_id: string;
	isExist: boolean;
	/** @nullable */
	notes: string | null;
	payment_type: PaymentsPaymentType;
	paymentDate: string;
	paymentDetails?: PaymentDetails;
	paymentDetails_id: string;
	/** @nullable */
	private_notes: string | null;
	/** @nullable */
	reference_number: string | null;
	/** @nullable */
	updatedAt: string | null;
	user?: User;
	user_id: string;
}
