/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { PaymentsControllerUpdate200AllOf } from "./paymentsControllerUpdate200AllOf";

export type PaymentsControllerUpdate200 = SuccessResponseDto & PaymentsControllerUpdate200AllOf;
