/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { PaymentsDtoPaymentType } from "./paymentsDtoPaymentType";

export interface PaymentsDto {
	amount: number;
	createdAt: string;
	id: string;
	invoice_id: string;
	isExist: boolean;
	/** @nullable */
	notes: string | null;
	payment_type: PaymentsDtoPaymentType;
	paymentDate: string;
	paymentDetails_id: string;
	/** @nullable */
	private_notes: string | null;
	/** @nullable */
	reference_number: string | null;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
}
