/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { PlanFeaturesDtoFeature } from "./planFeaturesDtoFeature";

export interface PlanFeaturesDto {
	count: number;
	createdAt: string;
	feature: PlanFeaturesDtoFeature;
	id: string;
	isExist: boolean;
	plan_id: string;
	/** @nullable */
	updatedAt: string | null;
}
