/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type PlanFeaturesDtoFeature =
	(typeof PlanFeaturesDtoFeature)[keyof typeof PlanFeaturesDtoFeature];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlanFeaturesDtoFeature = {
	Invoice: "Invoice",
	Quotation: "Quotation",
	Customer: "Customer",
	Product: "Product",
	Tax: "Tax",
	HSNCode: "HSNCode",
	ProductUnit: "ProductUnit",
	PaymentDetails: "PaymentDetails",
	InvoiceSettings: "InvoiceSettings",
	QuotationSettings: "QuotationSettings",
	Payments: "Payments",
	GateWayDetails: "GateWayDetails",
	AIDashboard: "AIDashboard",
} as const;
