/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface PlansDto {
	createdAt: string;
	days: number;
	description: string;
	id: string;
	is_active: boolean;
	isExist: boolean;
	name: string;
	price: number;
	/** @nullable */
	updatedAt: string | null;
}
