/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CurrenciesDto } from "./currenciesDto";
import type { ProductWithAllDataDtoType } from "./productWithAllDataDtoType";
import type { ProductUnitDto } from "./productUnitDto";

export interface ProductWithAllDataDto {
	createdAt: string;
	currency?: CurrenciesDto;
	currency_id: string;
	/** @nullable */
	description: string | null;
	/** @nullable */
	hsnCode_id: string | null;
	id: string;
	isExist: boolean;
	name: string;
	price: number;
	/** @nullable */
	tax_id: string | null;
	type: ProductWithAllDataDtoType;
	unit?: ProductUnitDto;
	unit_id: string;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
}
