/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Currencies } from "./currencies";
import type { ProductHsnCode } from "./productHsnCode";
import type { ProductTax } from "./productTax";
import type { ProductType } from "./productType";
import type { ProductUnit } from "./productUnit";
import type { User } from "./user";

export interface Product {
	createdAt: string;
	currency?: Currencies;
	currency_id: string;
	/** @nullable */
	description: string | null;
	/** @nullable */
	hsnCode?: ProductHsnCode;
	/** @nullable */
	hsnCode_id: string | null;
	id: string;
	isExist: boolean;
	name: string;
	price: number;
	/** @nullable */
	tax?: ProductTax;
	/** @nullable */
	tax_id: string | null;
	type: ProductType;
	unit?: ProductUnit;
	unit_id: string;
	/** @nullable */
	updatedAt: string | null;
	user?: User;
	user_id: string;
}
