/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { ProductUnitDto } from "./productUnitDto";

export type ProductunitControllerCreate201AllOf = {
	result?: ProductUnitDto;
};
