/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type ProductDtoType = (typeof ProductDtoType)[keyof typeof ProductDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductDtoType = {
	Service: "Service",
	Good: "Good",
} as const;
