/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { ProductunitControllerUpdate200AllOf } from "./productunitControllerUpdate200AllOf";

export type ProductunitControllerUpdate200 = SuccessResponseDto &
	ProductunitControllerUpdate200AllOf;
