/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { ExpensesDto } from "./expensesDto";
import type { InvoiceDto } from "./invoiceDto";

export interface ProfitLostReportsDto {
	expenses: ExpensesDto[];
	invoices: InvoiceDto[];
}
