/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { QuotationControllerMarkedAsRejected200AllOf } from "./quotationControllerMarkedAsRejected200AllOf";

export type QuotationControllerMarkedAsRejected200 = SuccessResponseDto &
	QuotationControllerMarkedAsRejected200AllOf;
