/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { QuotationControllerConvertToInvoice200AllOf } from "./quotationControllerConvertToInvoice200AllOf";

export type QuotationControllerConvertToInvoice200 = SuccessResponseDto &
	QuotationControllerConvertToInvoice200AllOf;
