/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { QuotationtemplateControllerUpdate200AllOf } from "./quotationtemplateControllerUpdate200AllOf";

export type QuotationtemplateControllerUpdate200 = SuccessResponseDto &
	QuotationtemplateControllerUpdate200AllOf;
