/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Agridulture API
 * Enhance your business with Agriculture API
 * OpenAPI spec version: 1.0
 */

export interface RedSoilDto {
	address: string;
	cereal: number;
	createdAt: string;
	groundnut: number;
	id: string;
	isExist: boolean;
	kagi: number;
	latitude: number;
	longitude: number;
	pulse: number;
	/** @nullable */
	updatedAt: string | null;
	vegetable: number;
}
