/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface ResetPasswordTokenDto {
	/** New password */
	password: string;
	/** Password reset token */
	token: string;
}
