/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface ShippingAddressDto {
	address: string;
	city: string;
	country_id: string;
	createdAt: string;
	id: string;
	isExist: boolean;
	state_id: string;
	/** @nullable */
	updatedAt: string | null;
	zip: string;
}
