/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Agridulture API
 * Enhance your business with Agriculture API
 * OpenAPI spec version: 1.0
 */
import type { RedSoilDto } from "./redSoilDto";

export type SoilControllerCreateRedSoil200AllOf = {
	result?: RedSoilDto;
};
