/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Agridulture API
 * Enhance your business with Agriculture API
 * OpenAPI spec version: 1.0
 */

export type SoilControllerGetRedSoilParams = {
	latitude: number;
	longitude: number;
};
