/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Agridulture API
 * Enhance your business with Agriculture API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { SoilControllerCreateRedSoil200AllOf } from "./soilControllerCreateRedSoil200AllOf";

export type SoilControllerCreateRedSoil200 = SuccessResponseDto &
	SoilControllerCreateRedSoil200AllOf;
