/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Agridulture API
 * Enhance your business with Agriculture API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { SoilControllerCreateBlackSoil200AllOf } from "./soilControllerCreateBlackSoil200AllOf";

export type SoilControllerCreateBlackSoil200 = SuccessResponseDto &
	SoilControllerCreateBlackSoil200AllOf;
