/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Agridulture API
 * Enhance your business with Agriculture API
 * OpenAPI spec version: 1.0
 */
import type { BlackSoilDto } from "./blackSoilDto";

export type SoilControllerCreateBlackSoil200AllOf = {
	result?: BlackSoilDto;
};
