/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { TaxDto } from "./taxDto";

export type TaxcodeControllerUpdate201AllOf = {
	result?: TaxDto;
};
