/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface UpdateCurrencyCompanyDto {
	address: string;
	city: string;
	companyName: string;
	country: string;
	currency_id: string;
	logo?: string;
	phoneNumber?: string;
	state: string;
	vat?: string;
	zipCode: string;
}
