/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { UpdateProductDtoType } from "./updateProductDtoType";

export interface UpdateProductDto {
	currency_id?: string;
	/** @nullable */
	description?: string | null;
	/** @nullable */
	hsnCode_id?: string | null;
	name?: string;
	price?: number;
	/** @nullable */
	tax_id?: string | null;
	type?: UpdateProductDtoType;
	unit_id?: string;
	user_id?: string;
}
