/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface UpdateInvoiceSettingsDto {
	autoArchive?: boolean;
	companyAddressTemplate?: string;
	customerBillingAddressTemplate?: string;
	customerShippingAddressTemplate?: string;
	dueNotice?: number;
	/** @nullable */
	footer?: string | null;
	invoicePrefix?: string;
	invoiceTemplateId?: string;
	/** @nullable */
	notes?: string | null;
	overDueNotice?: number;
	user_id?: string;
}
