/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { UpdateAIDashboardDtoType } from "./updateAIDashboardDtoType";

export interface UpdateAIDashboardDto {
	prompt?: string;
	query?: string;
	title?: string;
	type?: UpdateAIDashboardDtoType;
	user_id?: string;
}
