/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { UpdateCustomerDtoOption } from "./updateCustomerDtoOption";

export interface UpdateCustomerDto {
	billingAddress_id?: string;
	currencies_id?: string;
	display_name?: string;
	email?: string;
	name?: string;
	option?: UpdateCustomerDtoOption;
	/** @nullable */
	phone?: string | null;
	shippingAddress_id?: string;
	user_id?: string;
	/** @nullable */
	website?: string | null;
}
