/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface UpdateCompanyDto {
	/** @nullable */
	address?: string | null;
	/** @nullable */
	city?: string | null;
	/** @nullable */
	country_id?: string | null;
	/** @nullable */
	logo?: string | null;
	name?: string;
	/** @nullable */
	phone?: string | null;
	/** @nullable */
	state_id?: string | null;
	user_id?: string;
	/** @nullable */
	vat?: string | null;
	/** @nullable */
	zip?: string | null;
}
