/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { UpdatePaymentsDtoPaymentType } from "./updatePaymentsDtoPaymentType";

export interface UpdatePaymentsDto {
	amount?: number;
	invoice_id?: string;
	/** @nullable */
	notes?: string | null;
	payment_type?: UpdatePaymentsDtoPaymentType;
	paymentDate?: string;
	paymentDetails_id?: string;
	/** @nullable */
	private_notes?: string | null;
	/** @nullable */
	reference_number?: string | null;
	user_id?: string;
}
