/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { UpdateGateWayDetailsDtoType } from "./updateGateWayDetailsDtoType";

export interface UpdateGateWayDetailsDto {
	enabled?: boolean;
	/** @nullable */
	key?: string | null;
	/** @nullable */
	secret?: string | null;
	type?: UpdateGateWayDetailsDtoType;
	user_id?: string;
}
