/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export type UpdateCustomerDtoOption =
	(typeof UpdateCustomerDtoOption)[keyof typeof UpdateCustomerDtoOption];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateCustomerDtoOption = {
	Freelancer: "Freelancer",
	BusinessWithGST: "BusinessWithGST",
	BusinessWithoutGST: "BusinessWithoutGST",
} as const;
