/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { UserplansControllerCreate200AllOf } from "./userplansControllerCreate200AllOf";

export type UserplansControllerCreate200 = SuccessResponseDto & UserplansControllerCreate200AllOf;
