/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface UserPlansDto {
	createdAt: string;
	end_date: string;
	id: string;
	isExist: boolean;
	plan_id: string;
	session_id: string;
	start_date: string;
	status: boolean;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
}
