/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { VendorsBillingAddress } from "./vendorsBillingAddress";
import type { User } from "./user";

export interface Vendors {
	billingAddress?: VendorsBillingAddress;
	billingAddress_id: string;
	createdAt: string;
	display_name: string;
	email: string;
	id: string;
	isExist: boolean;
	name: string;
	/** @nullable */
	phone: string | null;
	/** @nullable */
	updatedAt: string | null;
	user?: User;
	user_id: string;
	/** @nullable */
	website: string | null;
}
